'use client';
import {useState,useEffect,useRef} from 'react';
import {Play,Pause,ArrowRight,Check,RotateCcw,Volume2,BookOpen,CheckCircle2,Headphones} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {toast} from 'sonner';
import {PARTS,normalizeText,type Question,type Attempt} from '@/lib/study-model';
export function SpeechPlayer({text,label='播放音频'}:{text:string;label?:string}){
 const [playing,setPlaying]=useState(false);const [rate,setRate]=useState('1');const utter=useRef<SpeechSynthesisUtterance|null>(null);
 useEffect(()=>()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel();},[text]);
 const play=()=>{if(!('speechSynthesis'in window)){toast.error('当前浏览器不支持系统朗读，请换用 Safari 或 Chrome');return;}if(playing){window.speechSynthesis.cancel();setPlaying(false);return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=Number(rate);const voice=window.speechSynthesis.getVoices().find(v=>v.lang==='en-US')||window.speechSynthesis.getVoices().find(v=>v.lang.startsWith('en'));if(voice)u.voice=voice;u.onend=()=>setPlaying(false);u.onerror=()=>setPlaying(false);utter.current=u;setPlaying(true);window.speechSynthesis.speak(u);};
 return <div className="audio-player"><button className="play-circle" aria-label={playing?'停止朗读':label} onClick={play}>{playing?<Pause size={18}/>:<Play size={18} fill="currentColor"/>}</button><div className="audio-meta"><b>{label}</b><small>原创练习 · 系统朗读</small></div><div className={'wave '+(playing?'playing':'')} aria-hidden="true">{Array.from({length:25},(_,i)=><i key={i} style={{height:(8+(i*13%24))+'px',animationDelay:(i*.06)+'s'}}/>)}</div><Select value={rate} onValueChange={v=>{setRate(v);if(playing){window.speechSynthesis.cancel();setPlaying(false);}}}><SelectTrigger aria-label="语速" className="speed-select"><SelectValue/></SelectTrigger><SelectContent>{['0.7','0.85','1','1.15'].map(r=><SelectItem key={r} value={r}>{r}×</SelectItem>)}</SelectContent></Select></div>
}
export default function Practice({queue,attempts,onAttempt,onClose,onFinish}:{queue:Question[];attempts:Attempt[];onAttempt:(a:Attempt)=>void;onClose:()=>void;onFinish:(minutes:number)=>void}){
 const [index,setIndex]=useState(0);const [choice,setChoice]=useState('');const [submitted,setSubmitted]=useState(false);const [correct,setCorrect]=useState(0);const [finished,setFinished]=useState(false);const [dictation,setDictation]=useState('');const [dictationDone,setDictationDone]=useState(false);const start=useRef(Date.now());const qStart=useRef(Date.now());
 const initialAttempts=useRef(new Set(attempts.map(a=>a.qid)));const q=queue[index];const hadAttempt=initialAttempts.current.has(q?.id);const transcript=q?.transcript||q?.audioText||'';const sentence=transcript.split(/(?<=[.!?])\s+/)[0]||'';
 const submit=()=>{if(choice===''||submitted)return;const ok=Number(choice)===q.correctIndex;const a:Attempt={id:crypto.randomUUID(),qid:q.id,choice:Number(choice),correct:ok,createdAt:new Date().toISOString(),seconds:Math.min(7200,Math.round((Date.now()-qStart.current)/1000)),mode:hadAttempt?'review':'first'};onAttempt(a);setSubmitted(true);if(ok)setCorrect(c=>c+1);};
 const next=()=>{if(index===queue.length-1){setFinished(true);return;}window.speechSynthesis?.cancel();setIndex(i=>i+1);setChoice('');setSubmitted(false);setDictation('');setDictationDone(false);qStart.current=Date.now();};
 if(!q)return null;
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="practice-dialog"><DialogHeader><DialogTitle>{finished?'这一小步，完成了。':`Part ${q.part} · ${PARTS[q.part-1]}`}</DialogTitle><DialogDescription>{finished?'保留这次收获，下一次从这里继续。':`原创起步包 · ${hadAttempt?'复练，首次答案已保留':'首次作答'} · ${index+1} / ${queue.length}`}</DialogDescription></DialogHeader>
 {!finished?<><Progress value={(index/queue.length)*100} className="thin-progress"/><div className="question-scroll" key={q.id}><div className="question-head"><span className="pill">{q.skill}</span><span className="muted small">{q.difficulty}</span></div>{q.image&&<img className="question-image" src={q.image} alt="办公室会议场景，请根据图片作答"/>}{q.passage&&<div className="passage" lang="en">{q.passage}</div>}{q.part<=4&&<SpeechPlayer key={q.id} text={q.audioText||q.transcript||q.prompt} label="听一遍，再选择"/>}<h3 className="question-prompt" lang="en">{q.part===2&&!submitted?'Listen to the question and choose the best response.':q.prompt}</h3>
 <RadioGroup value={choice} onValueChange={setChoice} disabled={submitted} className="answer-options" aria-label="选择答案">{q.options.map((option,i)=><label htmlFor={'answer-'+i} key={i} className={'answer-option '+(choice===String(i)?'selected ':'')+(submitted?(i===q.correctIndex?'correct':choice===String(i)?'incorrect':''):'')}><RadioGroupItem id={'answer-'+i} value={String(i)}/><span className="option-letter">{'ABCD'[i]}</span><span lang="en">{q.part<=2&&!submitted?'选项 '+ 'ABCD'[i]:option}</span>{submitted&&i===q.correctIndex&&<Check size={18}/>}</label>)}</RadioGroup>
 {submitted&&<div className="answer-feedback"><div className={'result-line '+(Number(choice)===q.correctIndex?'good':'bad')}>{Number(choice)===q.correctIndex?<CheckCircle2 size={19}/>:<RotateCcw size={19}/>}<b>{Number(choice)===q.correctIndex?'判断正确':'找到了一个值得巩固的地方'}</b><span>答案 {'ABCD'[q.correctIndex]}</span></div><Tabs defaultValue="explain"><TabsList className="lesson-tabs"><TabsTrigger value="explain">答案解析</TabsTrigger>{transcript&&<TabsTrigger value="listen">精听与听写</TabsTrigger>}<TabsTrigger value="vocab">词汇与表达</TabsTrigger></TabsList><TabsContent value="explain" className="tab-reading"><p>{q.explanation}</p><blockquote lang="en">{q.evidence}</blockquote>{q.translation&&<p className="muted">{q.translation}</p>}</TabsContent>{transcript&&<TabsContent value="listen" className="tab-reading"><p className="section-label">逐句回听 · 点一句，听一句</p><div className="transcript-lines">{transcript.split(/(?<=[.!?])\s+/).filter(Boolean).map((line,i)=><SpeechPlayer key={i} text={line} label={line}/>)}</div><div className="dictation"><h4>听写第一句</h4><p className="muted small">再听一遍，尝试写下第一句。标点和大小写不计。</p><textarea aria-label="听写答案" value={dictation} onChange={e=>{setDictation(e.target.value);setDictationDone(false);}} placeholder="Type what you hear…"/><button className="button secondary" onClick={()=>setDictationDone(true)} disabled={!dictation.trim()}>核对听写</button>{dictationDone&&<p className={normalizeText(dictation)===normalizeText(sentence)?'good':'muted'}>{normalizeText(dictation)===normalizeText(sentence)?'听写正确。现在试着跟读一次。':'对照原句：'+sentence}</p>}</div></TabsContent>}<TabsContent value="vocab" className="tab-reading">{q.vocabulary?.length?q.vocabulary.map(v=><div className="vocab-entry" key={v.word}><div><b lang="en">{v.word}</b><span>{v.meaning}</span></div><p lang="en">{v.example}</p></div>):<p>本题重点：{q.skill}。复习时先找出答案依据，再读完整句。</p>}</TabsContent></Tabs></div>}</div><div className="practice-footer"><span className="small muted">{submitted?'答案已保存 · 复习会保留首次记录':'按第一反应作答，先不查词'}</span><button className="button primary" disabled={!submitted&&choice===''} onClick={submitted?next:submit}>{submitted?(index===queue.length-1?'完成本组':'下一题'):'确认答案'}<ArrowRight size={17}/></button></div></>:<div className="session-complete"><CheckCircle2 size={42}/><h2>{correct}<small> / {queue.length} 题</small></h2><p>这组练习已经记录。样题表现不换算为正式分数。</p><button className="button primary" onClick={()=>onFinish(Math.max(1,Math.round((Date.now()-start.current)/60000)))}>记录时间与收获<ArrowRight size={17}/></button><button className="text-button" onClick={onClose}>先休息一下</button></div>}</DialogContent></Dialog>
}
