'use client';
import {useState,useEffect,useRef} from 'react';
import {Mic,Square,Play,RotateCcw,CheckCircle2,Timer} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import {type Speaking,type Recording} from '@/lib/study-model';
import {SpeechPlayer} from './practice';
export default function SpeakingRoom({prompt,onClose,onSave,onFinish}:{prompt:Speaking;onClose:()=>void;onSave:(r:Recording,b:Blob)=>Promise<void>;onFinish:(n:number)=>void}){
 const [phase,setPhase]=useState<'ready'|'prep'|'recording'|'done'>('ready');const [seconds,setSeconds]=useState(prompt.prepSeconds);const [url,setUrl]=useState('');const [saved,setSaved]=useState(false);const [busy,setBusy]=useState(false);const [self,setSelf]=useState<string[]>([]);const [note,setNote]=useState('');const [saveError,setSaveError]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const chunks=useRef<Blob[]>([]);const started=useRef(0);const last=useRef<{meta:Recording;blob:Blob}|null>(null);const objectURL=useRef('');const mounted=useRef(true);const beginning=useRef(false);const requestGeneration=useRef(0);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;requestGeneration.current++;if(recorder.current?.state==='recording'){recorder.current.onstop=null;recorder.current.stop();}stream.current?.getTracks().forEach(t=>t.stop());if(objectURL.current)URL.revokeObjectURL(objectURL.current);};},[]);
 const persist=async(meta:Recording,blob:Blob)=>{const gen=requestGeneration.current;try{await onSave(meta,blob);if(!mounted.current||gen!==requestGeneration.current||last.current?.meta.id!==meta.id)return;setSaved(true);setSaveError(false);toast.success('录音已保存');}catch{if(!mounted.current||gen!==requestGeneration.current||last.current?.meta.id!==meta.id)return;setSaveError(true);toast.error('录音暂未保存，请重试或下载保留');}};
 const begin=()=>{if(!stream.current||beginning.current||recorder.current?.state==='recording')return;beginning.current=true;const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));const r=new MediaRecorder(stream.current,mime?{mimeType:mime}:undefined);recorder.current=r;chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data);};r.onstop=async()=>{beginning.current=false;stream.current?.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:r.mimeType||'audio/webm'});if(!mounted.current)return;if(!blob.size){toast.error('没有收到录音，请检查麦克风');setPhase('ready');return;}if(objectURL.current)URL.revokeObjectURL(objectURL.current);objectURL.current=URL.createObjectURL(blob);setUrl(objectURL.current);setPhase('done');const meta:Recording={id:crypto.randomUUID(),promptId:prompt.id,title:prompt.title,duration:Math.round((Date.now()-started.current)/1000),createdAt:new Date().toISOString(),mime:blob.type,note};last.current={meta,blob};await persist(meta,blob);};r.start(250);started.current=Date.now();setPhase('recording');setSeconds(prompt.answerSeconds);};
 const start=async()=>{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast.error('当前浏览器不支持录音，请在 Safari 或 Chrome 中打开');return;}setBusy(true);const gen=++requestGeneration.current;try{const acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current||gen!==requestGeneration.current){acquired.getTracks().forEach(t=>t.stop());return;}stream.current=acquired;beginning.current=false;setSelf([]);setSaved(false);setPhase('prep');setSeconds(prompt.prepSeconds);}catch{toast.error('需要麦克风权限才能录音，可在浏览器设置中允许');}finally{setBusy(false);}};
 const stop=()=>{if(recorder.current?.state==='recording')recorder.current.stop();};
 useEffect(()=>{if(phase!=='prep'&&phase!=='recording')return;const t=setInterval(()=>setSeconds(n=>n-1),1000);return()=>clearInterval(t);},[phase]);
 useEffect(()=>{if(seconds>0)return;if(phase==='prep')begin();if(phase==='recording')stop();},[seconds,phase]);
 return <Dialog open onOpenChange={open=>{if(!open){if(phase==='recording'||phase==='prep'){toast('先结束录音，再离开练习');return;}onClose();}}}><DialogContent className="practice-dialog speaking-dialog"><DialogHeader><DialogTitle>{prompt.title}</DialogTitle><DialogDescription>原创口语专项 · 练习与自评，不换算正式成绩</DialogDescription></DialogHeader><div className="question-scroll"><div className="speaking-timer"><div className={'timer-dial '+phase}><Mic size={22}/><b>{phase==='done'?<CheckCircle2 size={35}/>:String(Math.max(0,seconds)).padStart(2,'0')}</b><small>{phase==='recording'?'正在录音':phase==='prep'?'准备时间':phase==='done'?'录音完成':'秒准备'}</small></div><div><p className="eyebrow">SPEAK, THEN REFLECT</p><h3>{phase==='recording'?'慢一点，也可以说清楚。':'先组织思路，再开口。'}</h3><p className="muted small">准备 {prompt.prepSeconds} 秒 · 作答 {prompt.answerSeconds} 秒</p></div></div>
 {prompt.image&&<img className="question-image" src={prompt.image} alt="口语练习办公室图片"/>}<p className="question-prompt" lang="en">{prompt.prompt}</p>{prompt.passage&&<div className="passage" lang="en">{prompt.passage}</div>}
 {phase==='ready'&&<><p className="muted small">点击后申请麦克风权限，准备倒计时结束会自动开始录音。</p><button className="button primary" disabled={busy} onClick={start}><Mic size={17}/>{busy?'等待麦克风…':'开始准备'}</button></>}{phase==='prep'&&<button className="button secondary" onClick={begin}>准备好了，现在录音<Play size={17}/></button>}{phase==='recording'&&<button className="button recording-stop" onClick={stop}><Square size={16} fill="currentColor"/>结束录音</button>}
 {phase==='done'&&<div className="speaking-review"><audio controls src={url} className="recording-player"/><p className="small muted">{saved?'录音已保存在本机，联网后同步。':'正在保存录音…'}</p>{saveError&&<div className="button-row"><button className="button secondary" onClick={()=>last.current&&persist(last.current.meta,last.current.blob)}>重试保存</button><a href={url} download="speaking-recording.webm" className="text-button">下载录音</a></div>}<h3>回听时，只改一个地方</h3><div className="self-checks">{prompt.guide.map(g=><label key={g}><Checkbox checked={self.includes(g)} onCheckedChange={v=>setSelf(s=>v?[...s,g]:s.filter(x=>x!==g))}/><span>{g}</span></label>)}</div><details className="sample-answer"><summary>看看一种表达方式</summary><p lang="en">{prompt.sampleAnswer}</p><SpeechPlayer text={prompt.sampleAnswer} label="听示范表达"/></details><div className="button-row"><button className="button secondary" disabled={!saved&&!saveError} onClick={start}><RotateCcw size={16}/>再说一次</button><button className="button primary" disabled={!saved} onClick={()=>onFinish(Math.max(1,Math.ceil(((last.current?.meta.duration||0)+prompt.prepSeconds)/60)))}>记录收获</button></div></div>}</div></DialogContent></Dialog>
}
