'use client';
import {useState,useEffect} from 'react';
import {Flame,Compass,BookOpen,Headphones,Mic,RotateCcw,ChartNoAxesCombined,Library,Settings2,ArrowUpRight,ArrowRight,Check,CheckCircle2,Clock,Sun,Moon,Sparkles,Download,Cloud,CloudOff,RefreshCw,ChevronRight,Target,Feather,CalendarDays,Play,NotebookPen,Monitor,Smartphone} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarGroupLabel} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {useStudy} from '@/lib/use-study';
import {registerNativeBack} from '@/lib/native-host';
import {PARTS,dayKey,daysUntil,dayOffset,getWeek,firstAttempts,reviewSchedule,chooseQuestions,type Profile,type Question,type Speaking,type Recording,type Theme} from '@/lib/study-model';
import qData from '@/content/questions.json';
import sData from '@/content/speaking.json';
import ResourceLibrary from './learn/resource-library';
import ExamCollection from './learn/exam-collection';
import Practice from './learn/practice';
import SpeakingRoom from './learn/speaking';
const questions=qData as Question[];const prompts=sData as Speaking[];
const NAV=[{id:'today',label:'今日旅程',en:'TODAY',icon:Compass},{id:'train',label:'训练之境',en:'PRACTICE',icon:BookOpen},{id:'review',label:'温故知新',en:'REVIEW',icon:RotateCcw},{id:'progress',label:'成长足迹',en:'PROGRESS',icon:ChartNoAxesCombined},{id:'resources',label:'学习书库',en:'LIBRARY',icon:Library}];
const themes=[{id:'hollow',name:'深蓝圣巢',english:'HOLLOW KNIGHT',note:'幽蓝微光 · 安静专注',image:'/images/hollow-v2-wide.webp'},{id:'silk',name:'绯红丝歌',english:'SILKSONG',note:'绯红丝线 · 温暖前行',image:'/images/silk-v2-wide.webp'},{id:'paper',name:'晨光书页',english:'DAYLIGHT',note:'明亮纸面 · 轻盈阅读',image:'/images/hollow-v2-wide.webp'}];
function saveFile(name:string,text:string,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function ChoiceSelect({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="form-select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
export default function StudyApp({owner,nativeMode=false}:{owner:string|null;nativeMode?:boolean}){
 const {data,ready,sync,syncNow,saveProfile,addAttempt,addCheckin,addRecording,recordingUrl}=useStudy(owner);
 const [nav,setNav]=useState('today');const [settings,setSettings]=useState(false);const [themeOpen,setThemeOpen]=useState(false);const [installOpen,setInstallOpen]=useState(false);const [draft,setDraft]=useState<Profile>(data.profile);const [queue,setQueue]=useState<Question[]|null>(null);const [speaking,setSpeaking]=useState<Speaking|null>(null);const [checkinOpen,setCheckinOpen]=useState(false);const [minutes,setMinutes]=useState('5');const [load,setLoad]=useState<'轻'|'刚好'|'重'>('刚好');const [note,setNote]=useState('');const [selectedResource,setSelectedResource]=useState<{id:string;title:string}|null>(null);const [trainingTab,setTrainingTab]=useState('lr');const [recordingPlay,setRecordingPlay]=useState<{url:string;title:string}|null>(null);const [installPrompt,setInstallPrompt]=useState<any>(null);const [now,setNow]=useState(new Date());
 const profile=data.profile;const today=dayKey(now,profile.timezone);const countdown=daysUntil(profile.examDate,today);const week=getWeek(data,today);const starts=week.filter(d=>d.started).length;const weekMinutes=week.reduce((a,b)=>a+b.minutes,0);const first=firstAttempts(data.attempts);const schedule=reviewSchedule(data.attempts);const due=schedule.filter(x=>x.isDue||x.wrong);const todayAttempts=data.attempts.filter(x=>dayKey(x.createdAt,profile.timezone)===today);const todayRecordings=data.recordings.filter(x=>dayKey(x.createdAt,profile.timezone)===today);const todayMinutes=data.checkins.filter(c=>c.date===today).reduce((n,c)=>n+c.minutes,0);const theme=themes.find(t=>t.id===profile.theme)||themes[0];
 useEffect(()=>registerNativeBack(()=>{
  if(speaking)return true; // SpeakingRoom owns recording and unsaved-audio protection.
  if(recordingPlay){if(recordingPlay.url.startsWith('blob:'))URL.revokeObjectURL(recordingPlay.url);setRecordingPlay(null);return true;}
  if(checkinOpen){setCheckinOpen(false);setSelectedResource(null);return true;}
  if(themeOpen){setThemeOpen(false);return true;}
  if(settings){setSettings(false);return true;}
  if(installOpen){setInstallOpen(false);return true;}
  if(queue){setQueue(null);return true;}
  if(nav!=='today'){setNav('today');return true;}
  return false;
 }),[speaking,recordingPlay,checkinOpen,themeOpen,settings,installOpen,queue,nav]);
 useEffect(()=>{document.documentElement.dataset.theme=profile.theme;},[profile.theme]);
 useEffect(()=>{const t=setInterval(()=>setNow(new Date()),60000);if(!nativeMode&&'serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const before=(e:Event)=>{e.preventDefault();setInstallPrompt(e);};window.addEventListener('beforeinstallprompt',before);return()=>{clearInterval(t);window.removeEventListener('beforeinstallprompt',before);};},[]);
 const partStats=PARTS.map((name,i)=>{const a=first.filter(a=>questions.find(q=>q.id===a.qid)?.part===i+1);return {part:i+1,name,total:a.length,correct:a.filter(x=>x.correct).length,rate:a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):null};});
 const weakest=partStats.filter(x=>x.total>0).sort((a,b)=>(a.rate||0)-(b.rate||0))[0];
 const pickPart=(isListening:boolean)=>{const relevant=partStats.filter(x=>isListening?x.part<=4:x.part>4);const tried=relevant.filter(x=>x.total>0).sort((a,b)=>(a.rate||0)-(b.rate||0));if(tried[0]&&(tried[0].rate||0)<70)return tried[0].part;return relevant.find(x=>x.total===0)?.part||relevant[Math.floor(Date.now()/86400000)%relevant.length].part;};
 const listeningPart=pickPart(true),readingPart=pickPart(false);const oral=prompts[data.recordings.length%prompts.length];
 const startPart=(part?:number,count=100)=>{const q=chooseQuestions(questions,data.attempts,part,count);if(q.length)setQueue(q);};
 const startDaily=(minimum=false)=>{const q=minimum?chooseQuestions(questions,data.attempts,listeningPart,1):[...chooseQuestions(questions,data.attempts,listeningPart,Math.max(1,Math.round(profile.dailyMinutes/12))),...chooseQuestions(questions,data.attempts,readingPart,Math.max(2,Math.round(profile.dailyMinutes/8)))];setQueue(q);};
 const finish=(n:number)=>{setQueue(null);setSpeaking(null);setMinutes(String(n));setNote('');setSelectedResource(null);setLoad('刚好');setCheckinOpen(true);};
 const changeTheme=(t:string)=>{if(!saveProfile({...profile,theme:t as Theme}))return;toast.success('主题已切换');};
 const openSettings=()=>{setDraft({...profile});setSettings(true);};
 const currentNav=NAV.find(x=>x.id===nav)!;
 const checkedTasks=[todayAttempts.some(a=>(questions.find(q=>q.id===a.qid)?.part||99)<=4),todayAttempts.some(a=>(questions.find(q=>q.id===a.qid)?.part||0)>4),todayRecordings.length>0];
 const startReview=()=>{const ids=new Set(due.map(x=>x.qid));const qs=questions.filter(q=>ids.has(q.id));if(qs.length)setQueue(qs);};
 const downloadRecap=()=>{const s=`# 微光托业 · 周复盘\n\n日期：${today}\n近7天启动：${starts}天\n已记录学习：${weekMinutes}分钟\n听读首次作答：${first.length}题\n口语录音：${data.recordings.length}段\n${weakest?`优先巩固：Part ${weakest.part} ${weakest.name}`:'尚未完成基线，不估分'}\n\n## 学习反馈\n${data.checkins.filter(c=>c.date>=dayOffset(today,-6)).map(c=>`- ${c.date} · ${c.minutes}分钟 · ${c.load}：${c.note||'未填写卡点'}`).join('\n')}\n\n漏一天不补两天。练习表现与正式成绩分开记录。`;saveFile('lantern-weekly-review.md',s,'text/markdown');};
 return <SidebarProvider style={{'--sidebar-width':'232px'} as React.CSSProperties}><Sidebar className="study-sidebar"><SidebarHeader className="side-brand"><div className="brand-mark"><Flame size={25}/></div><div><span className="brand-word">LANTERN</span><small>微 光 托 业</small></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel className="nav-caption">你的学习世界</SidebarGroupLabel><SidebarMenu>{NAV.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={nav===n.id} onClick={()=>setNav(n.id)} className="nav-button"><n.icon size={19}/><span>{n.label}</span>{n.id==='review'&&due.length>0&&<em>{due.length}</em>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><div className="side-chapter"><Feather size={23}/><p>每一小步<br/>都有回响。</p><div className="hairline"/><small>以自己的节奏，继续前行。</small></div></SidebarContent><SidebarFooter className="side-footer"><button onClick={()=>setThemeOpen(true)} className="side-theme"><span className={'theme-orb '+profile.theme}/><div><small>当前主题</small><b>{theme.name}</b></div><Settings2 size={15}/></button><button className="account-button" onClick={openSettings}><span className="avatar">{profile.name.slice(0,1)}</span><div><b>{profile.name}</b><small>目标与学习偏好</small></div><ChevronRight size={16}/></button></SidebarFooter></Sidebar>
 <main className="workspace"><header className="topbar"><div className="breadcrumb"><Flame className="mobile-logo" size={19}/><span>LANTERN</span><span className="divider-slash">/</span><b>{currentNav.label}</b></div><div className="topbar-actions"><button className="sync-button" onClick={()=>void syncNow()} title="同步学习记录">{sync==='synced'?<Cloud size={15}/>:sync==='loading'?<RefreshCw className="spin" size={15}/>:<CloudOff size={15}/>}<span>{sync==='synced'?'已同步':sync==='loading'?'同步中':sync==='local'?'本机保存':'等待同步'}</span></button><button className="icon-button" onClick={()=>setInstallOpen(true)} aria-label="安装手机应用"><Smartphone size={18}/></button><button className="icon-button" onClick={()=>setThemeOpen(true)} aria-label="选择主题"><Moon size={18}/></button></div></header>
 <div className="page-content"><div className="page-heading"><div><p className="eyebrow">{currentNav.en} / YOUR LEARNING PATH</p><h1>{currentNav.label}<span className="heading-dot">.</span></h1></div><div className="date-label"><CalendarDays size={16}/>{new Intl.DateTimeFormat('zh-CN',{timeZone:profile.timezone,month:'long',day:'numeric',weekday:'long'}).format(now)}</div></div>
 {!ready?<div className="panel loading-panel">正在整理你的学习记录…</div>:<>
 {nav==='today'&&<><section className="journey-hero"><div className="hero-vignette"/><div className="hero-content"><span className="hero-label"><span className="tiny-diamond"/>今日的微光</span><h2>{profile.theme==='silk'?<>循着丝线，<br/>继续向上。</>:profile.theme==='paper'?<>翻开今天，<br/>学会一点。</>:<>在寂静深处，<br/>点亮下一程。</>}</h2><p>{todayMinutes>0?`今天已记录 ${todayMinutes} 分钟。按自己的节奏继续。`:`给自己 ${profile.dailyMinutes} 分钟，从一小步开始。`}</p><div className="hero-actions"><button className="button hero-primary" onClick={()=>startDaily()}><Play size={16} fill="currentColor"/>开始今日练习<ArrowRight size={17}/></button><button className="hero-minimum" onClick={()=>startDaily(true)}>今天只学 5 分钟</button></div></div><div className="hero-caption"><span>{theme.english}</span><small>{theme.name} · 主题灵感</small></div></section>
 <div className="dashboard-grid"><section className="daily-section"><div className="section-heading"><h2>今天，完成这几件小事</h2><span>{checkedTasks.filter(Boolean).length} / 3</span></div><div className="task-list">{[{icon:Headphones,tag:`LISTENING / PART ${listeningPart}`,title:PARTS[listeningPart-1],detail:'先听作答，再精听一个卡点',time:Math.max(2,Math.round(profile.dailyMinutes*.4)),onClick:()=>startPart(listeningPart,2)},{icon:BookOpen,tag:`READING / PART ${readingPart}`,title:PARTS[readingPart-1],detail:'找到答案依据，弄懂一个错因',time:Math.max(2,Math.round(profile.dailyMinutes*.4)),onClick:()=>startPart(readingPart,3)},{icon:Mic,tag:'SPEAKING / SAY IT OUT LOUD',title:oral?.title||'开口说一次',detail:'录音、回听，只改一个地方',time:Math.max(1,Math.round(profile.dailyMinutes*.2)),onClick:()=>setSpeaking(oral)}].map((t,i)=><button className={'task-row '+(checkedTasks[i]?'task-done':'')} key={t.tag} onClick={t.onClick}><span className={'task-icon task-icon-'+i}>{checkedTasks[i]?<Check size={22}/>:<t.icon size={22}/>}</span><span className="task-body"><small>{t.tag}</small><b>{t.title}</b><span>{t.detail}</span></span><span className="task-tail"><span><Clock size={13}/>{t.time} 分钟</span><ArrowUpRight size={20}/></span></button>)}</div><div className="gentle-note"><Feather size={17}/><span>忙时做 5 分钟也算启动。漏一天，不欠补课债。</span></div></section>
 <aside className="dashboard-aside"><section className="goal-card panel"><div className="card-top"><span><Target size={17}/>我的目标</span><button onClick={openSettings} aria-label="编辑目标"><Settings2 size={16}/></button></div><div className="goal-scores"><div><small>听力与阅读</small><strong>{profile.lrGoal}<span>+</span></strong><span className="score-label">LISTENING & READING</span></div><div><small>口语表达</small><strong>{profile.speakingGoal}</strong><span className="score-label">SPEAKING</span></div></div><div className="exam-countdown"><CalendarDays size={16}/><span>{countdown===null?'尚未设置考期':countdown>0?<>距离考试还有 <b>{countdown}</b> 天</>:countdown===0?'今天考试，平稳发挥':'考期已到，更新下一程目标'}</span><small>{profile.examDate}</small></div></section><section className="week-card panel"><div className="card-top"><span>近 7 天的微光</span><span className="week-count">{starts}<small> / {profile.weeklyTarget} 天</small></span></div><div className="week-dots">{week.map(d=><div key={d.date}><span className={(d.started?'lit ':'')+(d.date===today?'is-today':'')}>{d.started?<Check size={16}/>:<i/>}</span><small>{['日','一','二','三','四','五','六'][new Date(d.date+'T12:00:00Z').getUTCDay()]}</small></div>)}</div><p>{starts===0?'从今天点亮第一束光。':`已经启动 ${starts} 天，记录了 ${weekMinutes} 分钟。`}</p></section></aside></div>
 <section className="coach-strip"><div className="coach-symbol"><Sparkles size={23}/></div><div><p className="eyebrow">TONY'S NOTE / 托尼老师</p><h3>{weakest?`下一次，先巩固 ${weakest.name}。`:'先留下起点，再慢慢走远。'}</h3><p>{weakest?`Part ${weakest.part} 已有 ${weakest.total} 道首次记录。先弄懂一处错误，再用新题复测。`:'首周先完成几次小练习，留下一段录音。不根据少量样题估分。'}</p></div><button className="text-button" onClick={()=>setNav('progress')}>查看学习反馈<ArrowRight size={16}/></button></section></>}
 {nav==='train'&&<><div className="section-intro"><p>挑一项练习，走完“作答 → 理解 → 再练”的小循环。</p><span className="pill">原创起步包 · {questions.length} 道听读 / {prompts.length} 类口语</span></div><Tabs value={trainingTab} onValueChange={setTrainingTab}><TabsList className="main-tabs"><TabsTrigger value="lr"><Headphones size={16}/>听力与阅读</TabsTrigger><TabsTrigger value="speaking"><Mic size={16}/>口语表达</TabsTrigger></TabsList><TabsContent value="lr"><div className="part-grid">{partStats.map(p=><button className="part-card panel" key={p.part} onClick={()=>startPart(p.part)}><div className="part-number">0{p.part}<span>{p.part<=4?<Headphones size={20}/>:<BookOpen size={20}/>}</span></div><h2>{p.name}</h2><p>{questions.filter(q=>q.part===p.part).length} 道原创练习</p><div className="part-status"><span>{p.rate===null?'尚未开始':`首次正确率 ${p.rate}%`}</span><ArrowUpRight size={18}/></div></button>)}</div><div className="practice-pack panel"><div><h3>综合练习 · {questions.length} 题</h3><p className="muted">包含全部起步题。用于练习流程，不作为 200 题完整模考。</p></div><button className="button secondary" onClick={()=>setQueue(questions)}>开始综合练习<ArrowRight size={17}/></button></div></TabsContent><TabsContent value="speaking"><div className="speaking-grid">{prompts.map((p,i)=><button key={p.id} className="speaking-card panel" onClick={()=>setSpeaking(p)}><span className="eyebrow">SPEAKING / 0{i+1}</span><h2>{p.title}</h2><p>{p.prompt.slice(0,100)}</p><div><span><Clock size={14}/>{p.prepSeconds} 秒准备 · {p.answerSeconds} 秒回答</span><Mic size={19}/></div></button>)}</div><p className="gentle-note">专项练习包含录音回听、示范表达和自评清单。AI 自动评分尚未启用。</p><RecordingList recordings={data.recordings} onPlay={async r=>setRecordingPlay({url:await recordingUrl(r),title:r.title})}/></TabsContent></Tabs></>}
 {nav==='review'&&<><div className="review-banner panel"><div className="review-symbol"><RotateCcw size={31}/></div><div><p className="eyebrow">A LITTLE REMEMBERING</p><h2>{due.length?`${due.length} 道题，值得再见一次。`:'把学过的，慢慢变成熟悉的。'}</h2><p>{due.length?'先回想，再作答。每次复练都会保留最初的答案。':'做完练习后，这里会按作答表现安排复习。'}</p></div>{due.length>0&&<button className="button primary" onClick={startReview}>开始复习<ArrowRight size={17}/></button>}</div>{schedule.length?<div className="review-list">{schedule.map(s=>{const q=questions.find(q=>q.id===s.qid);if(!q)return null;return <button key={q.id} className="review-row" onClick={()=>setQueue([q])}><div className={'review-state '+(s.wrong?'needs-work':'')}><BookOpen size={19}/></div><div><small>PART {q.part} · {q.skill}</small><h3>{q.title}</h3><p>{s.wrong?'上次作答有误，先找出判断依据':`连续答对 ${s.streak} 次 · 下次 ${dayKey(new Date(s.due),profile.timezone)}`}</p></div><span className="pill">{s.wrong?'待巩固':s.isDue?'今日复习':'已安排'}</span><ChevronRight size={17}/></button>})}</div>:<div className="empty-state"><BookOpen size={36}/><h3>第一份复习卡，等你来写</h3><p>完成一组练习，就会自动建立复习记录。</p><button className="button secondary" onClick={()=>startPart(5,3)}>从 3 道阅读题开始</button></div>}</>}
 {nav==='progress'&&<><div className="metrics-grid">{[{label:'近7天学习时间',value:weekMinutes,unit:'分钟',icon:Clock},{label:'近7天启动',value:starts,unit:'天',icon:Flame},{label:'听读首次作答',value:first.length,unit:'题',icon:BookOpen},{label:'口语录音',value:data.recordings.length,unit:'段',icon:Mic}].map(m=><div key={m.label} className="metric panel"><div><span>{m.label}</span><m.icon size={17}/></div><strong>{m.value}<small>{m.unit}</small></strong></div>)}</div><div className="progress-columns"><section className="panel"><div className="section-heading"><h2>每一小步，都算数</h2><span>近 7 天</span></div><div className="bar-chart" role="img" aria-label={'近7天学习分钟：'+week.map(x=>x.date+' '+x.minutes).join('，')}>{week.map(d=><div key={d.date} className="chart-column"><span>{d.minutes||'—'}</span><div className="bar-track"><i style={{height:Math.max(2,d.minutes/Math.max(30,...week.map(x=>x.minutes))*100)+'%'}} className={d.started?'active':''}/></div><small>{d.date.slice(5).replace('-','/')}</small></div>)}</div></section><section className="panel"><div className="section-heading"><h2>题型掌握情况</h2><span>仅首次作答</span></div><div className="part-progress">{partStats.map(p=><div key={p.part}><div><span>Part {p.part} · {p.name}</span><small>{p.rate===null?'待测':`${p.correct}/${p.total} · ${p.rate}%`}</small></div><Progress value={p.rate||0}/></div>)}</div><p className="small muted">练习正确率不等同正式成绩；完整模考基线仍需单独测量。</p></section></div><section className="panel recap-panel"><div className="section-heading"><h2>托尼老师 · 周复盘</h2><button className="text-button" onClick={downloadRecap}><Download size={15}/>导出复盘</button></div><p>{weekMinutes===0?'先积累真实记录，再判断学习负荷。今天只需完成一次小练习。':`近7天启动 ${starts} 天，实际记录 ${weekMinutes} 分钟。${data.checkins.filter(c=>c.date>=dayOffset(today,-6)&&c.load==='重').length>=2?'你有多次反馈负荷重，建议下周减少每日任务。':'保持当前节奏，先把一个高频卡点练熟。'}`}</p><div className="journal">{data.checkins.length?data.checkins.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,7).map(c=><article key={c.id}><span>{c.date.slice(5).replace('-','/')}</span><div><b>{c.minutes} 分钟 <small>· 负荷{c.load}</small></b><p>{c.note||'完成一次练习，继续前行。'}</p></div></article>):<p className="muted">还没有学习手记。完成练习后写下一个卡点即可。</p>}</div></section></>}
 {nav==='resources'&&<><div className="section-intro"><p>把材料、练习和收获留在一起。</p><span className="pill">官方入口 + 原创内容</span></div><ExamCollection checkins={data.checkins} onRecord={r=>{setMinutes(String(r.minutes));setSelectedResource({id:r.id,title:r.title});setNote('');setLoad('刚好');setCheckinOpen(true);}}/><section className="resource-collection"><div className="resource-cover"><Library size={38}/><span>VOL. 02</span><h2>微光<br/>原创练习集</h2><small>LISTEN · READ · SPEAK</small></div><div><p className="eyebrow">THE OPEN COLLECTION</p><h2>从第一道题，积累自己的学习资源。</h2><p>{questions.length} 道听读练习、{prompts.length} 类口语任务，附答案依据、中文解析与表达示例。题目为原创练习，听力使用系统朗读。</p><div className="button-row"><button className="button primary" onClick={()=>setNav('train')}>打开练习<ArrowRight size={16}/></button><button className="button secondary" onClick={()=>saveFile('lantern-original-starter.json',JSON.stringify({version:'0.2.0',license:'CC-BY-4.0',attribution:'LANTERN 微光托业原创起步包',questions,prompts},null,2))}><Download size={16}/>下载原创题包</button></div><small>原创文本按 CC BY 4.0 分享；官方链接及主题素材单独标注。</small></div></section><ResourceLibrary checkins={data.checkins} onRecord={r=>{setMinutes(String(r.minutes));setSelectedResource({id:r.id,title:r.title});setNote('');setLoad('刚好');setCheckinOpen(true);}}/><section className="panel resource-note"><h3>共享内容，保留各自的学习记录</h3><p>原创题包可以导出分享。你的作答、录音和手记单独保存，不包含在公共题包中。官方题目与音频通过原网站访问。</p><button className="text-button" onClick={()=>saveFile('lantern-my-study-records.json',JSON.stringify({version:'1.0.0',exportedAt:new Date().toISOString(),...data},null,2))}>导出我的个人记录<Download size={15}/></button></section></>}
 </>}
 <footer className="app-footer"><span><Flame size={13}/> LANTERN · 每天一点微光</span><span>原创练习 v0.2 <i/> TOEIC 是 ETS 注册商标，本项目为独立学习工具。</span></footer></div></main>
 <nav className="mobile-nav" aria-label="主导航">{NAV.map(n=><button key={n.id} onClick={()=>{setNav(n.id);window.scrollTo({top:0});}} className={nav===n.id?'active':''}><n.icon size={21}/><span>{n.label}</span></button>)}</nav>
 {queue&&<Practice key={queue.map(q=>q.id).join()} queue={queue} attempts={data.attempts} onAttempt={addAttempt} onClose={()=>setQueue(null)} onFinish={finish}/>}
 {speaking&&<SpeakingRoom nativeMode={nativeMode} key={speaking.id} prompt={speaking} onClose={()=>setSpeaking(null)} onSave={addRecording} onFinish={finish}/>}
 <Dialog open={checkinOpen} onOpenChange={o=>{setCheckinOpen(o);if(!o)setSelectedResource(null);}}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>留下一点今天的收获</DialogTitle><DialogDescription>如实记录实际用时，5 分钟也算一次启动。</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const m=Number(minutes);if(!Number.isInteger(m)||m<1||m>240)return;if(!addCheckin({id:crypto.randomUUID(),date:today,minutes:m,load,note:selectedResource?`[资源:${selectedResource.id}] ${selectedResource.title}\n${note}`.slice(0,1000):note,createdAt:new Date().toISOString()}))return;setCheckinOpen(false);setSelectedResource(null);toast.success('今天的微光，记下了');}}>{selectedResource&&<p className="selected-resource-label">学习材料：{selectedResource.title}</p>}<label className="field">实际学习分钟<input required type="number" min="1" max="240" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><label className="field">今天的负荷</label><RadioGroup value={load} onValueChange={v=>setLoad(v as typeof load)} className="load-options">{['轻','刚好','重'].map(v=><label key={v}><RadioGroupItem value={v}/>{v}</label>)}</RadioGroup><label className="field">一个收获或卡点<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} placeholder="例如：时间表达容易听错；今天终于听清了 revised。"/></label><button className="button primary full-width" type="submit"><Check size={17}/>保存今天的记录</button></form></DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>设定你的下一程</DialogTitle><DialogDescription>目标和学习节奏都可以随时调整。</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(!saveProfile({...draft,name:draft.name.trim(),onboarded:true}))return;setSettings(false);toast.success('学习目标已更新');}}><label className="field">称呼<input required maxLength={40} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="form-grid"><label className="field">听读目标<input type="number" required min={10} max={990} step={5} value={draft.lrGoal} onChange={e=>setDraft({...draft,lrGoal:Number(e.target.value)})}/></label><label className="field">口语目标<input type="number" required min={0} max={200} step={10} value={draft.speakingGoal} onChange={e=>setDraft({...draft,speakingGoal:Number(e.target.value)})}/></label></div><label className="field">听读考试日期<input type="date" value={draft.examDate} onChange={e=>setDraft({...draft,examDate:e.target.value})}/></label><div className="form-grid"><label className="field">每天可用时间<ChoiceSelect label="每天学习分钟" value={String(draft.dailyMinutes)} onChange={v=>setDraft({...draft,dailyMinutes:Number(v)})} items={[5,15,25,45,60].map(v=>({value:String(v),label:v+' 分钟'}))}/></label><label className="field">每周启动目标<ChoiceSelect label="每周启动天数" value={String(draft.weeklyTarget)} onChange={v=>setDraft({...draft,weeklyTarget:Number(v)})} items={[3,4,5,6,7].map(v=>({value:String(v),label:v+' 天'}))}/></label></div><label className="field">学习时区<ChoiceSelect label="时区" value={draft.timezone} onChange={v=>setDraft({...draft,timezone:v})} items={[{value:'Asia/Shanghai',label:'北京时间'},{value:'Asia/Tokyo',label:'东京时间'},{value:'America/Los_Angeles',label:'美国太平洋时间'},{value:'Europe/London',label:'伦敦时间'},{value:'Etc/UTC',label:'UTC'}]}/></label><button type="submit" className="button primary full-width">保存目标<Check size={17}/></button></form></DialogContent></Dialog>
 <Dialog open={themeOpen} onOpenChange={setThemeOpen}><DialogContent className="theme-dialog"><DialogHeader><DialogTitle>选择你的学习世界</DialogTitle><DialogDescription>空洞骑士与丝之歌的氛围灵感，用原创场景陪伴每一程。</DialogDescription></DialogHeader><RadioGroup value={profile.theme} onValueChange={changeTheme} className="theme-options">{themes.map(t=><label className={'theme-option '+(profile.theme===t.id?'chosen':'')} key={t.id}><div className={'theme-image '+t.id} style={{backgroundImage:`url(${t.image})`}}><span>{t.english}</span></div><div className="theme-description"><div><h3>{t.name}</h3><p>{t.note}</p></div><RadioGroupItem value={t.id} aria-label={t.name}/></div></label>)}</RadioGroup><p className="small muted">主题为原创灵感设计，未使用游戏原图、角色或音乐。</p></DialogContent></Dialog>
 <Dialog open={installOpen} onOpenChange={setInstallOpen}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>把微光放到手机桌面</DialogTitle><DialogDescription>{nativeMode?'原生预览版在本机保存，云端同步尚未接入。':'网页版与手机 PWA 共用同一份学习记录。'}</DialogDescription></DialogHeader><div className="install-symbol"><Flame size={38}/></div>{nativeMode?<div className="install-instructions"><p><b>原生预览版</b><br/>练习、设置和录音保存在这台设备上。原生导出与云备份仍在开发中。</p><p>录音需要麦克风权限。这是原生测试版，跨端账号同步尚未接入。</p></div>:installPrompt?<button className="button primary" onClick={async()=>{await installPrompt.prompt();setInstallPrompt(null);}}>安装微光托业<Download size={17}/></button>:<div className="install-instructions"><p><b>iPhone / iPad</b><br/>用 Safari 打开本页，点“分享”→“添加到主屏幕”。</p><p><b>Android</b><br/>用 Chrome 打开本页，在菜单选择“安装应用”或“添加到主屏幕”。</p><p><b>电脑</b><br/>在支持安装的浏览器地址栏选择安装图标。</p></div>}<p className="small muted">{nativeMode?'学习记录和录音目前只保存在本机，请保留应用数据。':'当前手机形态为 PWA。录音需要麦克风权限；新页面和云端同步需要网络。原生安装包尚未发布。'}</p></DialogContent></Dialog>
 <Dialog open={!!recordingPlay} onOpenChange={o=>{if(!o){if(recordingPlay?.url.startsWith('blob:'))URL.revokeObjectURL(recordingPlay.url);setRecordingPlay(null);}}}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>{recordingPlay?.title}</DialogTitle><DialogDescription>回听自己的表达，找一个地方改进。</DialogDescription></DialogHeader>{recordingPlay&&<audio controls autoPlay src={recordingPlay.url} className="recording-player"/>}</DialogContent></Dialog><Toaster position="top-center" richColors/>
 </SidebarProvider>
}
function RecordingList({recordings,onPlay}:{recordings:Recording[];onPlay:(r:Recording)=>void}){return <section className="recording-list"><div className="section-heading"><h2>我的口语录音</h2><span>{recordings.length} 段</span></div>{recordings.length?recordings.slice().reverse().map(r=><button key={r.id} className="recording-row" onClick={()=>onPlay(r)}><span className="play-circle"><Play size={16}/></span><span><b>{r.title}</b><small>{r.createdAt.slice(0,10)} · {r.duration} 秒 · {r.uploaded?'已同步':'本机录音'}</small></span><Headphones size={18}/></button>):<div className="empty-inline">录下第一段回答，留住你的起点。</div>}</section>}
