'use client';
import {useState,useEffect} from 'react';
import {Flame,Compass,BookOpen,Headphones,Mic,RotateCcw,ChartNoAxesCombined,Library,Settings2,ArrowUpRight,ArrowRight,Check,CheckCircle2,Clock,Sun,Moon,Sparkles,Download,Cloud,CloudOff,RefreshCw,ChevronRight,Target,Feather,CalendarDays,Play,NotebookPen,Monitor,Smartphone,ShieldCheck,ExternalLink} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarGroupLabel} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {useStudy} from '@/lib/use-study';
import {createStudyBackup} from '@/lib/study-backup';
import {registerNativeBack} from '@/lib/native-host';
import {createId,expandQuestionGroups,PARTS,dayKey,daysUntil,dayOffset,getWeek,firstAttempts,reviewSchedule,chooseQuestions,dailyPlan,type Profile,type Question,type Speaking,type Recording,type Theme} from '@/lib/study-model';
import qData from '@/content/questions.json';
import sData from '@/content/speaking.json';
import ResourceLibrary from './learn/resource-library';
import ExamCollection from './learn/exam-collection';
import ThemeLibrary from './learn/theme-library';
import artCatalogue from '@/art/themes.json';
import mapScenes from '@/art/map-scenes.json';
import Practice from './learn/practice';
import SpeakingRoom from './learn/speaking';
const questions=qData as Question[];const prompts=sData as Speaking[];
const NAV=[{id:'today',label:'�����ó�',en:'TODAY',icon:Compass},{id:'train',label:'ѵ��֮��',en:'PRACTICE',icon:BookOpen},{id:'review',label:'�¹�֪��',en:'REVIEW',icon:RotateCcw},{id:'progress',label:'�ɳ��㼣',en:'PROGRESS',icon:ChartNoAxesCombined},{id:'resources',label:'ѧϰ���',en:'LIBRARY',icon:Library}];
const themes=artCatalogue.themes;
const ONLINE_SITE_URL='https://lantern-toeic-godnight.zhuangzeliang.chatgpt.site';
function saveFile(name:string,text:string,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function ChoiceSelect({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="form-select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
export default function StudyApp({owner,nativeMode=false}:{owner:string|null;nativeMode?:boolean}){
 const {data,ready,sync,issues,syncNow,retryIssue,saveProfile,addAttempt,addCheckin,addRecording,recordingUrl}=useStudy(owner);
 const [nav,setNav]=useState('today');const [settings,setSettings]=useState(false);const [themeOpen,setThemeOpen]=useState(false);const [installOpen,setInstallOpen]=useState(false);const [draft,setDraft]=useState<Profile>(data.profile);const [queue,setQueue]=useState<Question[]|null>(null);const [speaking,setSpeaking]=useState<Speaking|null>(null);const [checkinOpen,setCheckinOpen]=useState(false);const [minutes,setMinutes]=useState('5');const [load,setLoad]=useState<'��'|'�պ�'|'��'>('�պ�');const [note,setNote]=useState('');const [selectedResource,setSelectedResource]=useState<{id:string;title:string}|null>(null);const [trainingTab,setTrainingTab]=useState('lr');const [recordingPlay,setRecordingPlay]=useState<{url:string;title:string}|null>(null);const [installPrompt,setInstallPrompt]=useState<any>(null);const [now,setNow]=useState(new Date());
 const profile=data.profile;const today=dayKey(now,profile.timezone);const countdown=daysUntil(profile.examDate,today);const week=getWeek(data,today);const starts=week.filter(d=>d.started).length;const weekMinutes=week.reduce((a,b)=>a+b.minutes,0);const first=firstAttempts(data.attempts);const schedule=reviewSchedule(data.attempts);const due=schedule.filter(x=>x.isDue||x.wrong);const todayAttempts=data.attempts.filter(x=>dayKey(x.createdAt,profile.timezone)===today);const todayRecordings=data.recordings.filter(x=>dayKey(x.createdAt,profile.timezone)===today);const todayMinutes=data.checkins.filter(c=>c.date===today).reduce((n,c)=>n+c.minutes,0);const theme=themes.find(t=>t.id===profile.theme)||themes[0];
 useEffect(()=>registerNativeBack(()=>{
  if(speaking)return true; // SpeakingRoom owns recording and unsaved-audio protection.
  if(recordingPlay){if(recordingPlay.url.startsWith('blob:'))URL.revokeObjectURL(recordingPlay.url);setRecordingPlay(null);return true;}
  if(checkinOpen){setCheckinOpen(false);setSelectedResource(null);return true;}
  if(themeOpen){setThemeOpen(false);return true;}
  if(settings){setSettings(false);return true;}
  if(installOpen){setInstallOpen(false);return true;}
  if(queue){setQueue(null);return true;}
  if(nav!=='today'){setNav('today');return true;}
  return false;
 }),[speaking,recordingPlay,checkinOpen,themeOpen,settings,installOpen,queue,nav]);
 useEffect(()=>{const element=document.documentElement;element.dataset.theme=profile.theme;element.style.setProperty('--image',theme.image?`url(${theme.image})`:'none');element.style.setProperty('--image-mobile',theme.portrait?`url(${theme.portrait})`:'none');},[profile.theme,theme.image,theme.portrait]);
 useEffect(()=>{const t=setInterval(()=>setNow(new Date()),60000);if(!nativeMode&&'serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const before=(e:Event)=>{e.preventDefault();setInstallPrompt(e);};window.addEventListener('beforeinstallprompt',before);return()=>{clearInterval(t);window.removeEventListener('beforeinstallprompt',before);};},[]);
 const partStats=PARTS.map((name,i)=>{const a=first.filter(a=>questions.find(q=>q.id===a.qid)?.part===i+1);return {part:i+1,name,total:a.length,correct:a.filter(x=>x.correct).length,rate:a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):null};});
 const weakest=partStats.filter(x=>x.total>0).sort((a,b)=>(a.rate||0)-(b.rate||0))[0];
 const {listeningPart,readingPart,oral,checkedTasks}=dailyPlan(data,questions,prompts,today);
 const startPart=(part?:number,count=100)=>{const q=chooseQuestions(questions,data.attempts,part,count);if(q.length)setQueue(q);};
 const startDaily=(minimum=false)=>{const q=minimum?chooseQuestions(questions,data.attempts,listeningPart<=2?listeningPart:2,1):[...chooseQuestions(questions,data.attempts,listeningPart,Math.max(1,Math.round(profile.dailyMinutes/12))),...chooseQuestions(questions,data.attempts,readingPart,Math.max(2,Math.round(profile.dailyMinutes/8)))];setQueue(q);};
 const finish=(n:number)=>{setQueue(null);setSpeaking(null);setMinutes(String(n));setNote('');setSelectedResource(null);setLoad('�պ�');setCheckinOpen(true);};
 const changeTheme=(t:string)=>{if(!saveProfile({...profile,theme:t as Theme}))return;toast.success('�������л�');};
 const openSettings=()=>{setDraft({...profile});setSettings(true);};
 const currentNav=nav==='art'?{label:'�����زĿ�',en:'ART LIBRARY'}:NAV.find(x=>x.id===nav)!;
 const region=mapScenes.views[nav as keyof typeof mapScenes.views]||mapScenes.views.today;
 const startReview=()=>{const ids=new Set(due.map(x=>x.qid));const qs=expandQuestionGroups(questions,ids);if(qs.length)setQueue(qs);};
 const downloadRecap=()=>{const s=`# ΢����ҵ �� �ܸ���\n\n���ڣ�${today}\n��7��������${starts}��\n�Ѽ�¼ѧϰ��${weekMinutes}����\n�����״�����${first.length}��\n����¼����${data.recordings.length}��\n${weakest?`���ȹ��̣�Part ${weakest.part} ${weakest.name}`:'��δ��ɻ��ߣ�������'}\n\n## ѧϰ����\n${data.checkins.filter(c=>c.date>=dayOffset(today,-6)).map(c=>`- ${c.date} �� ${c.minutes}���� �� ${c.load}��${c.note||'δ��д����'}`).join('\n')}\n\n©һ�첻�����졣��ϰ��������ʽ�ɼ��ֿ���¼��`;saveFile('lantern-weekly-review.md',s,'text/markdown');};
 const regionSummary=nav==='today'?[['������ѧ',todayMinutes+' ����'],['������ϰ',todayAttempts.length+' ��'],['�������',todayRecordings.length+' ��']]:nav==='train'?[['�������Ķ�',questions.length+' ��ԭ����'],['�������',prompts.length+' ������'],['��ϰ��ʽ','���� �� ���� �� ����']]:nav==='review'?[['������',due.length+' ����'],['��ϰ��¼',schedule.length+' ����'],['�������','�Ȼ��룬������']]:nav==='progress'?[['�� 7 ��',weekMinutes+' ����'],['ѧϰ����',starts+' ��'],['�״��¼',first.length+' ����']]:[['������Դ','�ٷ����'],['��ϰ����','ԭ�����������'],['ѧϰ�ջ�','������']];
 const regionAction=nav==='today'?()=>startDaily():nav==='train'?()=>startPart(listeningPart,3):nav==='review'?(due.length?startReview:()=>startPart(5,3)):nav==='progress'?downloadRecap:()=>setNav('train');
 const regionActionLabel=nav==='today'?'��ʼ������ϰ':nav==='train'?'��ʼ������ϰ':nav==='review'?(due.length?'��ʼ��ϰ':'�� 3 ���Ķ��⿪ʼ'):nav==='progress'?'�������ܸ���':'��ԭ����ϰ';
 return <SidebarProvider className="atlas-app" style={{'--sidebar-width':'248px','--region-accent':region.accent} as React.CSSProperties}>
 <Sidebar className="study-sidebar"><SidebarHeader className="side-brand"><div className="brand-mark"><Flame size={25}/></div><div><span className="brand-word">LANTERN</span><small>΢����ҵ �� ѧϰ֮��</small></div></SidebarHeader>
 <SidebarContent><SidebarGroup><SidebarGroupLabel className="nav-caption">ѧϰ���� <span>STUDY</span></SidebarGroupLabel><SidebarMenu>{NAV.map(n=>{const map=mapScenes.views[n.id as keyof typeof mapScenes.views];return <SidebarMenuItem key={n.id}><SidebarMenuButton isActive={nav===n.id} aria-current={nav===n.id?'page':undefined} onClick={()=>{setNav(n.id);window.scrollTo({top:0});}} className="nav-button atlas-nav"><img src={map.thumbnail} alt="" width={58} height={58}/><span className="atlas-nav-copy"><b>{n.label}</b><small>{n.en}</small></span>{n.id==='review'&&due.length>0?<em>{due.length}</em>:<span className="nav-index">{map.chapter}</span>}</SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu></SidebarGroup>
 <div className="rest-stop"><img src={mapScenes.restImage} alt="С��ʿ�ڵ�������" width={640} height={360} loading="lazy"/><div><span>TAKE A BREAK</span><p>Ъһ�ᣬ�ٳ�����</p></div></div></SidebarContent>
 <SidebarFooter className="side-footer"><button onClick={()=>setThemeOpen(true)} className="side-theme"><span className={'theme-orb '+profile.theme}/><div><small>������ɫ</small><b>{theme.name}</b></div><Settings2 size={15}/></button><button className="account-button" onClick={openSettings}><span className="avatar">{profile.name.slice(0,1)}</span><div><b>{profile.name}</b><small>Ŀ����ѧϰƫ��</small></div><ChevronRight size={16}/></button></SidebarFooter></Sidebar>

 <main className="workspace atlas-workspace" data-region={nav}><header className="topbar atlas-statusbar" aria-label="ѧϰ״̬">
 <div className="traveller-label"><Flame size={19}/><div><b>����״̬</b><small>{new Intl.DateTimeFormat('zh-CN',{timeZone:profile.timezone,month:'long',day:'numeric'}).format(now)}</small></div></div>
 <div className="status-metrics"><div className="status-time"><Clock size={17}/><div><span>����ѧϰ</span><b>{ready?todayMinutes:'��'} <small>/ {profile.dailyMinutes} ����</small></b></div><Progress aria-label="����ѧϰʱ��" value={ready?Math.min(100,todayMinutes/profile.dailyMinutes*100):0}/></div><button onClick={()=>setNav('review')} className="status-review"><RotateCcw size={17}/><span>����ϰ <b>{ready?due.length:'��'}</b></span></button><button onClick={openSettings} className="status-goal"><Target size={17}/><span>����Ŀ�� <b>{profile.lrGoal}</b></span></button></div>
 <div className="topbar-actions"><button className="sync-button" onClick={()=>void syncNow()} title="ͬ��ѧϰ��¼">{sync==='synced'?<Cloud size={16}/>:sync==='loading'?<RefreshCw className="spin" size={16}/>:<CloudOff size={16}/>}<span>{sync==='synced'?'��ͬ��':sync==='loading'?'ͬ����':sync==='local'?'��������':sync==='blocked'?'ͬ���账��':'�ȴ�ͬ��'}</span></button><button className="icon-button" onClick={()=>setInstallOpen(true)} aria-label="��װ�ֻ�Ӧ��"><Smartphone size={18}/></button><button className="icon-button" onClick={()=>setThemeOpen(true)} aria-label="ѡ������"><Moon size={18}/></button><button className="icon-button mobile-settings" onClick={openSettings} aria-label="�༭Ŀ��"><Settings2 size={18}/></button></div></header>
 <div className="page-content atlas-content">
 {nav==='art'?<div className="page-heading"><div><p className="eyebrow">ART LIBRARY</p><h1>�����زĿ�</h1></div></div>:<section className="region-map" aria-labelledby="region-title">
 <picture className="region-art" key={region.image}><source media="(max-width: 767px)" srcSet={region.mobile}/><img src={region.image} width={1600} height={900} alt="" style={{objectPosition:region.position}} fetchPriority="high"/></picture>
 <div className="region-shade"/><div className="region-topline"><span><Compass size={15}/>{currentNav.en}</span><span>{region.chapter} / 05</span></div>
 <div className="region-copy"><h1 id="region-title">{currentNav.label}</h1><p>{region.description}</p><div className="region-actions"><button className="button region-primary" onClick={regionAction} disabled={!ready}>{nav==='progress'?<Download size={17}/>:<Play size={16} fill="currentColor"/>}{regionActionLabel}<ArrowRight size={17}/></button>{nav==='today'&&<button className="region-minimum" onClick={()=>startDaily(true)} disabled={!ready}>����ֻѧ 5 ����</button>}{nav==='train'&&<button className="region-minimum" onClick={()=>setSpeaking(oral)} disabled={!ready}><Mic size={16}/>��ϰ����</button>}</div></div>

 <div className="region-status">{regionSummary.map(([label,value])=><div key={label}><span>{label}</span><b>{ready?value:'��'}</b></div>)}</div>
 </section>}

 {issues.length>0&&<section className="sync-issues panel" aria-label="ͬ������"><h2>�м�¼��δͬ��</h2><p>������¼�ᱣ�������Լ���ѧϰ���Ժ�����</p>{issues.map(issue=><div key={issue.kind+issue.id}><div><b>{issue.kind==='recording'?(data.recordings.find(r=>r.id===issue.id)?.title||'����¼��'):issue.kind==='session'?'�˺�ͬ��':'ѧϰ��¼'}</b><p>{issue.reason}</p>{issue.status==='waiting'&&<small>�Զ����� {issue.attempts} / 3 �� �Ժ����</small>}</div><button className="text-button" disabled={sync==='loading'} onClick={()=>retryIssue(issue)}>���³���<RefreshCw size={14}/></button></div>)}</section>}
 {!ready?<div className="panel loading-panel">�����������ѧϰ��¼��</div>:<>
 {nav==='art'&&<ThemeLibrary selected={profile.theme} onApply={changeTheme} onBack={()=>setNav('today')}/>}
 {nav==='today'&&<>
 <div className="dashboard-grid"><section className="daily-section"><div className="section-heading"><h2>�����г�</h2><span>{checkedTasks.filter(Boolean).length} / 3 ������ϰ</span></div><div className="task-list">{[{icon:Headphones,tag:`LISTENING / PART ${listeningPart}`,title:PARTS[listeningPart-1],detail:'���������پ���һ������',time:Math.max(2,Math.round(profile.dailyMinutes*.4)),onClick:()=>startPart(listeningPart,2)},{icon:BookOpen,tag:`READING / PART ${readingPart}`,title:PARTS[readingPart-1],detail:'�ҵ������ݣ�Ū��һ������',time:Math.max(2,Math.round(profile.dailyMinutes*.4)),onClick:()=>startPart(readingPart,3)},{icon:Mic,tag:'SPEAKING / SAY IT OUT LOUD',title:oral?.title||'����˵һ��',detail:'¼����������ֻ��һ���ط�',time:Math.max(1,Math.round(profile.dailyMinutes*.2)),onClick:()=>setSpeaking(oral)}].map((t,i)=><button className={'task-row '+(checkedTasks[i]?'task-done':'')} key={t.tag} onClick={t.onClick}><img className="task-scene" src={mapScenes.taskImages[i]} width={640} height={360} alt="" loading="lazy"/><span className="task-order" aria-hidden="true">{String(i+1).padStart(2,'0')}</span><span className={'task-icon task-icon-'+i}>{checkedTasks[i]?<Check size={22}/>:<t.icon size={22}/>}</span><span className="task-body"><small>{t.tag}</small><b>{t.title}</b><span>{t.detail}</span></span><span className="task-tail"><span><Clock size={13}/>{t.time} ����</span><ArrowUpRight size={20}/></span></button>)}</div><div className="gentle-note"><Feather size={17}/><span>æʱ�� 5 ����Ҳ��������©һ�죬��Ƿ����ծ��</span></div></section>
 <aside className="dashboard-aside"><section className="goal-card panel"><div className="card-top"><span><Target size={17}/>�ҵ�Ŀ��</span><button onClick={openSettings} aria-label="�༭Ŀ��"><Settings2 size={16}/></button></div><div className="goal-scores"><div><small>�������Ķ�</small><strong>{profile.lrGoal}<span>+</span></strong><span className="score-label">LISTENING & READING</span></div><div><small>�������</small><strong>{profile.speakingGoal}</strong><span className="score-label">SPEAKING</span></div></div><div className="exam-countdown"><CalendarDays size={16}/><span>{countdown===null?'��δ���ÿ���':countdown>0?<>���뿼�Ի��� <b>{countdown}</b> ��</>:countdown===0?'���쿼�ԣ�ƽ�ȷ���':'�����ѵ���������һ��Ŀ��'}</span><small>{profile.examDate}</small></div></section><section className="week-card panel"><div className="card-top"><span>�� 7 ���΢��</span><span className="week-count">{starts}<small> / {profile.weeklyTarget} ��</small></span></div><div className="week-dots">{week.map(d=><div key={d.date}><span className={(d.started?'lit ':'')+(d.date===today?'is-today':'')}>{d.started?<Check size={16}/>:<i/>}</span><small>{['��','һ','��','��','��','��','��'][new Date(d.date+'T12:00:00Z').getUTCDay()]}</small></div>)}</div><p>{starts===0?'�ӽ��������һ���⡣':`�Ѿ����� ${starts} �죬��¼�� ${weekMinutes} ���ӡ�`}</p></section></aside></div>
 <section className="coach-strip"><div className="coach-symbol"><Sparkles size={23}/></div><div><p className="eyebrow">TONY'S NOTE / ������ʦ</p><h3>{weakest?`��һ�Σ��ȹ��� ${weakest.name}��`:'��������㣬��������Զ��'}</h3><p>{weakest?`Part ${weakest.part} ���� ${weakest.total} ���״μ�¼����Ū��һ�������������⸴�⡣`:'��������ɼ���С��ϰ������һ��¼��������������������֡�'}</p></div><button className="text-button" onClick={()=>setNav('progress')}>�鿴ѧϰ����<ArrowRight size={16}/></button></section></>}
 {nav==='train'&&<><div className="section-intro"><p>��һ����ϰ�����ꡰ���� �� ���� �� ��������Сѭ����</p><span className="pill">ԭ���𲽰� �� {questions.length} ������ / {prompts.length} �����</span></div><Tabs value={trainingTab} onValueChange={setTrainingTab}><TabsList className="main-tabs"><TabsTrigger value="lr"><Headphones size={16}/>�������Ķ�</TabsTrigger><TabsTrigger value="speaking"><Mic size={16}/>�������</TabsTrigger></TabsList><TabsContent value="lr"><div className="part-grid">{partStats.map(p=><button className="part-card panel" key={p.part} onClick={()=>startPart(p.part)}><div className="part-number">0{p.part}<span>{p.part<=4?<Headphones size={20}/>:<BookOpen size={20}/>}</span></div><h2>{p.name}</h2><p>{questions.filter(q=>q.part===p.part).length} ��ԭ����ϰ</p><div className="part-status"><span>{p.rate===null?'��δ��ʼ':`�״���ȷ�� ${p.rate}%`}</span><ArrowUpRight size={18}/></div></button>)}</div><div className="practice-pack panel"><div><h3>�ۺ���ϰ �� {questions.length} ��</h3><p className="muted">����ȫ�����⡣������ϰ���̣�����Ϊ 200 ������ģ����</p></div><button className="button secondary" onClick={()=>setQueue(questions)}>��ʼ�ۺ���ϰ<ArrowRight size={17}/></button></div></TabsContent><TabsContent value="speaking"><div className="speaking-grid">{prompts.map((p,i)=><button key={p.id} className="speaking-card panel" onClick={()=>setSpeaking(p)}><span className="eyebrow">SPEAKING / 0{i+1}</span><h2>{p.title}</h2><p>{p.prompt.slice(0,100)}</p><div><span><Clock size={14}/>{p.prepSeconds} ��׼�� �� {p.answerSeconds} ��ش�</span><Mic size={19}/></div></button>)}</div><p className="gentle-note">ר����ϰ����¼��������ʾ������������嵥��AI �Զ�������δ���á�</p><RecordingList recordings={data.recordings} onPlay={async r=>{try{setRecordingPlay({url:await recordingUrl(r),title:r.title});}catch(e){toast.error(e instanceof Error?e.message:'¼����ʱ�޷���ȡ�����Ժ�����');}}}/></TabsContent></Tabs></>}
 {nav==='review'&&<><div className="review-banner panel"><div className="review-symbol"><RotateCcw size={31}/></div><div><p className="eyebrow">A LITTLE REMEMBERING</p><h2>{due.length?`${due.length} ���⣬ֵ���ټ�һ�Ρ�`:'��ѧ���ģ����������Ϥ�ġ�'}</h2><p>{due.length?'�Ȼ��룬������ÿ�θ������ᱣ������Ĵ𰸡�':'������ϰ������ᰴ������ְ��Ÿ�ϰ��'}</p></div>{due.length>0&&<button className="button primary" onClick={startReview}>��ʼ��ϰ<ArrowRight size={17}/></button>}</div>{schedule.length?<div className="review-list">{schedule.map(s=>{const q=questions.find(q=>q.id===s.qid);if(!q)return null;return <button key={q.id} className="review-row" onClick={()=>setQueue(expandQuestionGroups(questions,new Set([q.id])))}><div className={'review-state '+(s.wrong?'needs-work':'')}><BookOpen size={19}/></div><div><small>PART {q.part} �� {q.skill}</small><h3>{q.title}</h3><p>{s.wrong?'�ϴ������������ҳ��ж�����':`������� ${s.streak} �� �� �´� ${dayKey(new Date(s.due),profile.timezone)}`}</p></div><span className="pill">{s.wrong?'������':s.isDue?'���ո�ϰ':'�Ѱ���'}</span><ChevronRight size={17}/></button>})}</div>:<div className="empty-state"><BookOpen size={36}/><h3>��һ�ݸ�ϰ����������д</h3><p>���һ����ϰ���ͻ��Զ�������ϰ��¼��</p><button className="button secondary" onClick={()=>startPart(5,3)}>�� 3 ���Ķ��⿪ʼ</button></div>}</>}
 {nav==='progress'&&<><div className="metrics-grid">{[{label:'��7��ѧϰʱ��',value:weekMinutes,unit:'����',icon:Clock},{label:'��7������',value:starts,unit:'��',icon:Flame},{label:'�����״�����',value:first.length,unit:'��',icon:BookOpen},{label:'����¼��',value:data.recordings.length,unit:'��',icon:Mic}].map(m=><div key={m.label} className="metric panel"><div><span>{m.label}</span><m.icon size={17}/></div><strong>{m.value}<small>{m.unit}</small></strong></div>)}</div><div className="progress-columns"><section className="panel"><div className="section-heading"><h2>ÿһС����������</h2><span>�� 7 ��</span></div><div className="bar-chart" role="img" aria-label={'��7��ѧϰ���ӣ�'+week.map(x=>x.date+' '+x.minutes).join('��')}>{week.map(d=><div key={d.date} className="chart-column"><span>{d.minutes||'��'}</span><div className="bar-track"><i style={{height:Math.max(2,d.minutes/Math.max(30,...week.map(x=>x.minutes))*100)+'%'}} className={d.started?'active':''}/></div><small>{d.date.slice(5).replace('-','/')}</small></div>)}</div></section><section className="panel"><div className="section-heading"><h2>�����������</h2><span>���״�����</span></div><div className="part-progress">{partStats.map(p=><div key={p.part}><div><span>Part {p.part} �� {p.name}</span><small>{p.rate===null?'����':`${p.correct}/${p.total} �� ${p.rate}%`}</small></div><Progress value={p.rate||0}/></div>)}</div><p className="small muted">��ϰ��ȷ�ʲ���ͬ��ʽ�ɼ�������ģ���������赥��������</p></section></div><section className="panel recap-panel"><div className="section-heading"><h2>������ʦ �� �ܸ���</h2><button className="text-button" onClick={downloadRecap}><Download size={15}/>��������</button></div><p>{weekMinutes===0?'�Ȼ�����ʵ��¼�����ж�ѧϰ���ɡ�����ֻ�����һ��С��ϰ��':`��7������ ${starts} �죬ʵ�ʼ�¼ ${weekMinutes} ���ӡ�${data.checkins.filter(c=>c.date>=dayOffset(today,-6)&&c.load==='��').length>=2?'���ж�η��������أ��������ܼ���ÿ������':'���ֵ�ǰ���࣬�Ȱ�һ����Ƶ�������졣'}`}</p><div className="journal">{data.checkins.length?data.checkins.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,7).map(c=><article key={c.id}><span>{c.date.slice(5).replace('-','/')}</span><div><b>{c.minutes} ���� <small>�� ����{c.load}</small></b><p>{c.note||'���һ����ϰ������ǰ�С�'}</p></div></article>):<p className="muted">��û��ѧϰ�ּǡ������ϰ��д��һ�����㼴�ɡ�</p>}</div></section></>}
 {nav==='resources'&&<><div className="section-intro"><p>�Ѳ��ϡ���ϰ���ջ�����һ��</p><span className="pill">�ٷ���� + ԭ������</span></div><ExamCollection checkins={data.checkins} onRecord={r=>{setMinutes(String(r.minutes));setSelectedResource({id:r.id,title:r.title});setNote('');setLoad('�պ�');setCheckinOpen(true);}}/><section className="resource-collection"><div className="resource-cover"><Library size={38}/><span>VOL. 02</span><h2>΢��<br/>ԭ����ϰ��</h2><small>LISTEN �� READ �� SPEAK</small></div><div><p className="eyebrow">THE OPEN COLLECTION</p><h2>�ӵ�һ���⣬�����Լ���ѧϰ��Դ��</h2><p>{questions.length} ��������ϰ��{prompts.length} ��������񣬸������ݡ����Ľ��������ʾ������ĿΪԭ����ϰ������ʹ��ϵͳ�ʶ���</p><div className="button-row"><button className="button primary" onClick={()=>setNav('train')}>����ϰ<ArrowRight size={16}/></button><button className="button secondary" onClick={()=>saveFile('lantern-original-starter.json',JSON.stringify({version:'0.2.0',license:'CC-BY-4.0',attribution:'LANTERN ΢����ҵԭ���𲽰�',questions,prompts},null,2))}><Download size={16}/>����ԭ�����</button></div><small>ԭ���ı��� CC BY 4.0 �������ٷ����Ӽ������زĵ�����ע��</small></div></section><ResourceLibrary checkins={data.checkins} onRecord={r=>{setMinutes(String(r.minutes));setSelectedResource({id:r.id,title:r.title});setNote('');setLoad('�պ�');setCheckinOpen(true);}}/><section className="panel resource-note"><h3>�������ݣ��������Ե�ѧϰ��¼</h3><p>ԭ��������Ե����������������¼�����ּǵ������棬�������ڹ�������С��ٷ���Ŀ����Ƶͨ��ԭ��վ���ʡ�</p><button className="text-button" onClick={()=>saveFile('lantern-my-study-records.json',JSON.stringify(createStudyBackup(data),null,2))}>�����ҵĸ��˼�¼<Download size={15}/></button></section></>}
 </>}
 <footer className="app-footer"><span><Flame size={13}/> LANTERN �� ÿ��һ��΢��</span><span>Ӧ�� v0.2.4 �� ԭ����ϰ v0.2 <i/> TOEIC �� ETS ע���̱꣬����ĿΪ����ѧϰ���ߡ�</span></footer></div></main>
 <nav className="mobile-nav" aria-label="������">{NAV.map(n=><button aria-current={nav===n.id?"page":undefined} key={n.id} onClick={()=>{setNav(n.id);window.scrollTo({top:0});}} className={nav===n.id?'active':''}><n.icon size={21}/><span>{n.label}</span></button>)}</nav>
 {queue&&<Practice key={queue.map(q=>q.id).join()} queue={queue} attempts={data.attempts} onAttempt={addAttempt} onClose={()=>setQueue(null)} onFinish={finish}/>}
 {speaking&&<SpeakingRoom nativeMode={nativeMode} key={speaking.id} prompt={speaking} onClose={()=>setSpeaking(null)} onSave={addRecording} onFinish={finish}/>}
 <Dialog open={checkinOpen} onOpenChange={o=>{setCheckinOpen(o);if(!o)setSelectedResource(null);}}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>����һ�������ջ�</DialogTitle><DialogDescription>��ʵ��¼ʵ����ʱ��5 ����Ҳ��һ��������</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const m=Number(minutes);if(!Number.isInteger(m)||m<1||m>240)return;if(!addCheckin({id:createId(),date:today,minutes:m,load,note:selectedResource?`[��Դ:${selectedResource.id}] ${selectedResource.title}\n${note}`.slice(0,1000):note,createdAt:new Date().toISOString()}))return;setCheckinOpen(false);setSelectedResource(null);toast.success('�����΢�⣬������');}}>{selectedResource&&<p className="selected-resource-label">ѧϰ���ϣ�{selectedResource.title}</p>}<label className="field">ʵ��ѧϰ����<input required type="number" min="1" max="240" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><label className="field">����ĸ���</label><RadioGroup value={load} onValueChange={v=>setLoad(v as typeof load)} className="load-options">{['��','�պ�','��'].map(v=><label key={v}><RadioGroupItem value={v}/>{v}</label>)}</RadioGroup><label className="field">һ���ջ�򿨵�<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} placeholder="���磺ʱ����������������������������� revised��"/></label><button className="button primary full-width" type="submit"><Check size={17}/>�������ļ�¼</button></form></DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>�趨�����һ��</DialogTitle><DialogDescription>Ŀ���ѧϰ���඼������ʱ������</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(!saveProfile({...draft,name:draft.name.trim(),onboarded:true}))return;setSettings(false);toast.success('ѧϰĿ���Ѹ���');}}><label className="field">�ƺ�<input required maxLength={40} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="form-grid"><label className="field">����Ŀ��<input type="number" required min={10} max={990} step={5} value={draft.lrGoal} onChange={e=>setDraft({...draft,lrGoal:Number(e.target.value)})}/></label><label className="field">����Ŀ��<input type="number" required min={0} max={200} step={10} value={draft.speakingGoal} onChange={e=>setDraft({...draft,speakingGoal:Number(e.target.value)})}/></label></div><label className="field">������������<input type="date" value={draft.examDate} onChange={e=>setDraft({...draft,examDate:e.target.value})}/></label><div className="form-grid"><label className="field">ÿ�����ʱ��<ChoiceSelect label="ÿ��ѧϰ����" value={String(draft.dailyMinutes)} onChange={v=>setDraft({...draft,dailyMinutes:Number(v)})} items={[5,15,25,45,60].map(v=>({value:String(v),label:v+' ����'}))}/></label><label className="field">ÿ������Ŀ��<ChoiceSelect label="ÿ����������" value={String(draft.weeklyTarget)} onChange={v=>setDraft({...draft,weeklyTarget:Number(v)})} items={[3,4,5,6,7].map(v=>({value:String(v),label:v+' ��'}))}/></label></div><label className="field">ѧϰʱ��<ChoiceSelect label="ʱ��" value={draft.timezone} onChange={v=>setDraft({...draft,timezone:v})} items={[{value:'Asia/Shanghai',label:'����ʱ��'},{value:'Asia/Tokyo',label:'����ʱ��'},{value:'America/Los_Angeles',label:'����̫ƽ��ʱ��'},{value:'Europe/London',label:'�׶�ʱ��'},{value:'Etc/UTC',label:'UTC'}]}/></label><button type="submit" className="button primary full-width">����Ŀ��<Check size={17}/></button></form></DialogContent></Dialog>
 <Dialog open={themeOpen} onOpenChange={setThemeOpen}><DialogContent className="theme-dialog"><DialogHeader><DialogTitle>ѡ������</DialogTitle><DialogDescription>ѡ���ʺ��Ķ�����ɫ��</DialogDescription></DialogHeader><RadioGroup value={profile.theme} onValueChange={changeTheme} className="theme-options">{themes.map(t=><label className={'theme-option '+(profile.theme===t.id?'chosen':'')} key={t.id}><div className={'theme-image '+t.id} style={{backgroundImage:t.image?`url(${t.image})`:'none'}}><span>{t.english}</span></div><div className="theme-description"><div><h3>{t.name}</h3><p>{t.note}</p></div><RadioGroupItem value={t.id} aria-label={t.name}/></div></label>)}</RadioGroup><button className="text-button" onClick={()=>{setThemeOpen(false);setNav('art');}}>��������ز�<ArrowUpRight size={16}/></button><p className="small muted">Ӧ���ز���ԭ���ο��ֿ�������</p></DialogContent></Dialog>
 <Dialog open={installOpen} onOpenChange={setInstallOpen}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>{nativeMode?'����ԭ��Ԥ�����ƶ�ѧϰ':'��΢��ŵ���������'}</DialogTitle><DialogDescription>{nativeMode?'����ԭ��Ԥ�����ڱ������棻��Ҫ���豸ͬ��ʱʹ�����߰档':owner?'��ʹ�� ChatGPT �˺ŵ�¼������ PWA ����ҳ�湲��ѧϰ��¼��':'��ǰ�Ǳ���Ԥ������ʽ˽��վ���¼���ͬ����'}</DialogDescription></DialogHeader><div className="install-symbol"><Flame size={38}/></div>{nativeMode?<><div className="install-account-state local"><CloudOff size={22}/><div><b>���ɱ���ģʽ</b><p>��ϰ�����ú�¼��������̨�豸����δ�������˺�ͬ����</p></div></div><div className="install-instructions"><p><b>����ԭ��Ԥ����</b><br/>¼����Ҫ��˷�Ȩ�ޡ��������Ӧ�����ݻ�ж�غ���װ�������������⡣</p></div><a className="button primary full-width" href={ONLINE_SITE_URL} target="_blank" rel="noopener noreferrer">��ͬ����ҳ��<ExternalLink size={17}/></a></>:<><div className="install-account-state"><ShieldCheck size={22}/><div><b>{owner?'�˺�ͬ���ѿ���':'����Ԥ��ģʽ'}</b><p>{owner?'�ں����ֻ��ϵ�¼ͬһ ChatGPT �˺ţ����ܼ�����ǰѧϰ��¼��':'������˽��վ�����Ҫ��ȫ��¼��'}</p></div></div>{installPrompt?<button className="button primary full-width" onClick={async()=>{await installPrompt.prompt();setInstallPrompt(null);}}>��װ΢����ҵ<Download size={17}/></button>:<div className="install-instructions"><p><b>HarmonyOS / ����</b><br/>��ϵͳ������򿪱�ҳ����������˵���ѡ�����������桱�򡰰�װӦ�á���</p></div>}</>}<p className="small muted">{nativeMode?'������ͬ��������Ϸ������߰沢��¼ͬһ ChatGPT �˺š�':'��ǰ�����ֻ���̬Ϊ PWA���ֻ��ŵ�¼�������ʵ������֤��ŻῪ�š�¼����Ҫ��˷�Ȩ�ޣ���ҳ����ƶ�ͬ����Ҫ���硣'}</p></DialogContent></Dialog>
 <Dialog open={!!recordingPlay} onOpenChange={o=>{if(!o){if(recordingPlay?.url.startsWith('blob:'))URL.revokeObjectURL(recordingPlay.url);setRecordingPlay(null);}}}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>{recordingPlay?.title}</DialogTitle><DialogDescription>�����Լ��ı����һ���ط��Ľ���</DialogDescription></DialogHeader>{recordingPlay&&<audio controls autoPlay src={recordingPlay.url} className="recording-player"/>}</DialogContent></Dialog><Toaster position="top-center" richColors/>
 </SidebarProvider>
}
function RecordingList({recordings,onPlay}:{recordings:Recording[];onPlay:(r:Recording)=>void}){return <section className="recording-list"><div className="section-heading"><h2>�ҵĿ���¼��</h2><span>{recordings.length} ��</span></div>{recordings.length?recordings.slice().reverse().map(r=><button key={r.id} className="recording-row" onClick={()=>onPlay(r)}><span className="play-circle"><Play size={16}/></span><span><b>{r.title}</b><small>{r.createdAt.slice(0,10)} �� {r.duration} �� �� {r.uploaded?'��ͬ��':'����¼��'}</small></span><Headphones size={18}/></button>):<div className="empty-inline">¼�µ�һ�λش���ס�����㡣</div>}</section>}
